trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
  
steps:
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
    verbose: true
    
- script: echo Hello!
  displayName: 'Run a one line scripts'
  
- script: |
    echo add a multiline
    echo one more line
  displayName: 'Run a multiline'
  
