trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
  
steps:
- script: echo Hello!
  displayName: 'Run a one line scripts'
  
- script: |
    echo add a multiline
    echo one more line
  displayname: 'Run a multiline '
  
